### ISSUE TITLE
Does not appear to work for linked actors

### ISSUE THREAD

**Issue by mageofthesands** [Fair-Strides/Fvtt-PF1E-Spellbook-Generator#1]
Module doesn't seem to work for linked actors.  Not using the macro with drag & drop as GM.  Nor by clicking Spellbook Generator.  I cannot drag spells from the NPC sheet either.    It only works if I drag from the Spells Browser, but that doubles the work.

Foundry version 9 build 269.  Pathfinder 1 v0.80.24  Spellbook Generator 1.1.
![spellbookgenerator](https://user-images.githubusercontent.com/81931767/171905176-5b91197e-3948-40bd-908d-5e2eadad9e26.jpg)

**Comment by splitlungs** [comment]
+1 I'm having the same problems

**Comment by Fair-Strides** [comment]
The linked actor functionality is for the purposes of creating the book item at the end. The module's intended use was for generating spellbook items for loot, or sharing purposes. The module also uses just the Spells browser so that it forms links to the spells in the book, which can't work if it's linking to something on a different actor's sheet.
